



#!!! README !!!

# After pressing run, resize console window height so "KLEIDI" is barely visible























from distutils.command.clean import clean
from re import A, T
from signal import raise_signal
import time
import os


### VARIABLES ###

# Get username



### FUNCTIONS ###


# TECHINICAL FUNCTIONS #

def empty(e):
    try:
        for i in range(e):
           print("")
    except:
        print("!ERROR! An error occured with an empty function.")

def slide(s):
    for i in range(s):
        print("")
        time.sleep(.1)

def skip():
    c = "aaaah" # Clear the checker variable from the last call
    while True: # Every tick...
        c = input("Press enter to continue: ") # ...get user input
        if c != "aaaah": # If checker variable does not equal input...
            break # ...break the loop so computer doesn't spontaneous combust.


# STORY FUNCTIONS #

def enter_password(): # Reurns password
    time.sleep(.5)
    userpw = input("Please enter a new password: ")
    userpw = input("please enter a more secure password: ")
    userpw = input("Please enter a valid password: ")
    print("(Don't forget it, you'll need this later) ")
    time.sleep(1)
    userpw = input("I said a SECURE PASSWORD: ")
    time.sleep(.5)
    empty(30)
    print("                             Now, was that so hard?")
    print("")
    print("                        Your password is: '" + userpw + "'")
    print("")
    print("")
    print("")
    print("")
    print("")
    empty(5)
    time.sleep(5)
    slide(30)
    return userpw

def enter_username(): # Reurns username
    empty(35)
    time.sleep(.5)
    print("!!README!! remember your username, you'll need this later in the game!")
    print("")
    name = input("Please enter a username: ")
    empty(30)
    print("SUCCESS! Account created with username '" + name + "'")
    empty(10)
    time.sleep(3)
    slide(30)
    return name

def splashscreen():


    print("              oooo    oooo oooo             o8o        .o8   o8o                ")
    time.sleep(.1)
    print("              `888   .8P'  `888             `''       '888   '''                ")
    time.sleep(.1)
    print("               888  d8'     888   .ooooo.  oooo   .oooo888  oooo                ")
    time.sleep(.1)
    print("               88888[       888  d88' `88b `888  d88' `888  `888                ")
    time.sleep(.1)
    print("               888`88b.     888  888ooo888  888  888   888   888                ")
    time.sleep(.1)
    print("               888  `88b.   888  888    .o  888  888   888   888                ")
    time.sleep(.1)
    print("               o888o  o888o o888o `Y8bod8P' o888o `Y8bod88P' o888o              ")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("                               -|             |-                                ")
    time.sleep(.1)
    print("           -|                  [-_-_-_-_-_-_-_-]                  |-            ")
    time.sleep(.1)
    print("           [-_-_-_-_-]          |             |          [-_-_-_-_-]            ")
    time.sleep(.1)
    print("            | o   o |           [  0   0   0  ]           | o   o |             ")
    time.sleep(.1)
    print("             |     |    -|       |           |       |-    |     |              ")
    time.sleep(.1)
    print("             |     |_-___-___-___-|         |-___-___-___-_|     |              ")
    time.sleep(.1)
    print("             |  o  ]              [    0    ]              [  o  |              ")
    time.sleep(.1)
    print("             |     ]   o   o   o  [ _______ ]  o   o   o   [     | ----_________")
    time.sleep(.1)
    print("  _____----- |     ]              [ ||||||| ]              [     |              ")
    time.sleep(.1)
    print("             |     ]              [ ||||||| ]              [     |              ")
    time.sleep(.1)
    print("         _-_-|_____]--------------[_|||||||_]--------------[_____|-_-_          ")
    time.sleep(.1)
    print("        ( (__________------------_____________-------------_________) )         ")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("--------------------------------------------------------------------------------")
    time.sleep(.325)
    empty(30)
    time.sleep(.325)
    print("              oooo    oooo oooo             o8o        .o8   o8o                ")
    print("              `888   .8P'  `888             `''       '888   '''                ")
    print("               888  d8'     888   .ooooo.  oooo   .oooo888  oooo                ")
    print("               88888[       888  d88' `88b `888  d88' `888  `888                ")
    print("               888`88b.     888  888ooo888  888  888   888   888                ")
    print("               888  `88b.   888  888    .o  888  888   888   888                ")
    print("               o888o  o888o o888o `Y8bod8P' o888o `Y8bod88P' o888o              ")
    print("")
    print("                      The 80x25 Command Line Adventure!")
    print("                               -|             |-                                ")
    print("           -|                  [-_-_-_-_-_-_-_-]                  |-            ")
    print("           [-_-_-_-_-]          |             |          [-_-_-_-_-]            ")
    print("            | o   o |           [  0   0   0  ]           | o   o |             ")
    print("             |     |    -|       |           |       |-    |     |              ")
    print("             |     |_-___-___-___-|         |-___-___-___-_|     |              ")
    print("             |  o  ]              [    0    ]              [  o  |              ")
    print("             |     ]   o   o   o  [ _______ ]  o   o   o   [     | ----_________")
    print("  _____----- |     ]              [ ||||||| ]              [     |              ")
    print("             |     ]              [ ||||||| ]              [     |              ")
    print("         _-_-|_____]--------------[_|||||||_]--------------[_____|-_-_          ")
    print("        ( (__________------------_____________-------------_________) )         ")
    print("")
    print("--------------------------------------------------------------------------------")

def thankyou():
    print("Thank you for creating a free account! (charges may apply)")
    empty(12)
    time.sleep(3)
    empty(30)
    print("A random NFT has been added to your account to get you started!")
    empty(12)
    time.sleep(3)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  0                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 0 ether (0 USD)                                       |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("--------------------------------------------------------------------------------")
    time.sleep(3)
    empty(12)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                             A WILD NFT APPEARED!                             |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")
    time.sleep(3)

def phishing():

    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("                      ____                                                      ")
    time.sleep(.1)
    print("                     / ___`\                                                    ")
    time.sleep(.1)
    print("         /|         | (   \ \                                                   ")
    time.sleep(.1)
    print("    |^v^v  V|        \ \/) ) )                                                  ")
    time.sleep(.1)
    print("    \  ____ /         \_/ / /                                                   ")
    time.sleep(.1)
    print("    ,Y`    `,            / /                                                    ")
    time.sleep(.1)
    print("    ||  -  -)           {  }                                                    ")
    time.sleep(.1)
    print("    \\   _\ |           | |                                                     ")
    time.sleep(.1)
    print("     \\ / _`\_         / /                                                      ")
    time.sleep(.1)
    print("     /        ``\     _|_|                                                      ")
    time.sleep(.1)
    print("  ,-`          \ \  ,//(_}                                                      ")
    time.sleep(.1)
    print(" /              | \/  \| |                                                      ")
    time.sleep(.1)
    print("|               | '   ,\ \                                                      ")
    time.sleep(.1)
    print("|     |        /\  _/`  | |                                                     ")
    time.sleep(.1)
    print("\     |        | ``     | |                                                     ")
    time.sleep(.1)
    print(" |    \        |        | |                                                     ")
    time.sleep(.1)
    print(" |    |        |        / /                                                     ")
    time.sleep(.1)
    print(" |    |        |        | |                                                     ")
    time.sleep(.1)
    print("--------------------------------------------------------------------------------")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("")
    time.sleep(.1)

    empty(30)

    print("                      ____                                                      ")
    print("                     / ___`\         Greetings!                                 ")
    print("         /|         | (   \ \                                                   ")
    print("    |^v^v  V|        \ \/) ) )       My name is Mentes, and I am here to help   ")
    print("    \  ____ /         \_/ / /        you grow your new account!                 ")
    print("    ,Y`    `,            / /                                                    ")
    print("    ||  -  -)           {  }         I see you have come across quite a rare    ")
    print("    \\   _\ |           | |          collectable, please enter your password    ")
    print("     \\ / _`\_         / /           to confirm your identity so we may begin   ")
    print("     /        ``\     _|_|                                                      ")
    print("  ,-`          \ \  ,//(_}                                                      ")
    print(" /              | \/  \| |                                                      ")
    print("|               | '   ,\ \                                                      ")
    print("|     |        /\  _/`  | |                                                     ")
    print("\     |        | ``     | |                                                     ")
    print(" |    \        |        | |                                                     ")
    print(" |    |        |        / /                                                     ")
    print(" |    |        |        | |                                                     ")
    print("--------------------------------------------------------------------------------")
    print("")
    print("")
    print("")
    print("")

def meetmentor(): 
    print("                                                                /     |         ")
    time.sleep(.1)
    print("   _     _   _______   ___   _______   __                      /      |         ")
    time.sleep(.1)
    print("  | | _ | | |   _   | |   | |       | |  |                    /       |         ")
    time.sleep(.1)
    print("  | || || | |  |_|  | |   | |_     _| |  |               ___,'        |         ")
    time.sleep(.1)
    print("  |       | |       | |   |   |   |   |  |             <  -'          :         ")
    time.sleep(.1)
    print("  |       | |       | |   |   |   |   |__|              `-.__..--'``-,_\_       ")
    time.sleep(.1)
    print("  |   _   | |   _   | |   |   |   |    __                  |o/ ` :,.)_`>        ")
    time.sleep(.1)
    print("  |__| |__| |__| |__| |___|   |___|   |__|                 :/ `     ||/)        ")
    time.sleep(.1)
    print("                                                           (_.).__,-` |\        ")
    time.sleep(.1)
    print("  _____________________________________                    /( `.``   `| :       ")
    time.sleep(.1)
    print(" | Are you INSANE!?!?!?               |                    \'`-.)  `  ; ;       ")
    time.sleep(.1)
    print(" |                                    |                    | `       /-<        ")
    time.sleep(.1)
    print(" | You can't just give your password  |                    |     `  /   `.      ")
    time.sleep(.1)
    print(" | to just anyone!!!                  |    ,-_-..____     /|  `    :__..-'\     ")
    time.sleep(.1)
    print(" |                                    |   /,'-.__\\  ``-./ :`      ;       \    ")
    time.sleep(.1)
    print(" | YOU FOOL!!! Now you have to get    |   `\ `\  `\\  \ :  (   `  /  ,   `. \   ")
    time.sleep(.1)
    print(" | your password back from the hacker.|     \` \   \\   |  | `   :  :     .\ \  ")
    time.sleep(.1)
    print(" |____________________________________|      \ `\_  ))  :  ;     |  |      ): : ")
    time.sleep(.1)
    print("                                            (`-.-'\ ||  |\ \   ` ;  ;       | | ")
    time.sleep(.1)
    print("                                             \-_   `;;._   ( `  /  /_       | | ")
    time.sleep(.1)
    print("                                              `-.-.// ,'`-._\__/_,'         ; | ")
    time.sleep(.1)
    print("                                                 \:: :     /     `     ,   /  | ")
    time.sleep(.1)
    print("                                                  || |    (        ,' /   /   | ")
    time.sleep(.1)
    print("                                                  ||                ,'   /    | ")
    time.sleep(10)



    print("                                                                /     |         ")
    print("                                                               /      |         ")
    print("                                                              /       |         ")
    print("                                                         ___,'        |         ")
    print("                                                       <  -'          :         ")
    print("                                                        `-.__..--'``-,_\_       ")
    print("                                                           |o/ ` :,.)_`>        ")
    print("                                                           :/ `     ||/)        ")
    print("                                                           (_.).__,-` |\        ")
    print("  ____________________________________                     /( `.``   `| :       ")
    print(" | If you don't recover your password |                    \'`-.)  `  ; ;       ")
    print(" | soon, you're entire identity could |                    | `       /-<        ")
    print(" | be stolen!                         |                    |     `  /   `.      ")
    print(" |                                    |    ,-_-..____     /|  `    :__..-'\     ")
    print(" | *sigh...*  There are a few ways we |   /,'-.__\\  ``-./ :`      ;       \    ")
    print(" | could go about this...             |   `\ `\  `\\  \ :  (   `  /  ,   `. \   ")
    print(" |                                    |     \` \   \\   |  | `   :  :     .\ \  ")
    print(" |____________________________________|      \ `\_  ))  :  ;     |  |      ): : ")
    print("                                            (`-.-'\ ||  |\ \   ` ;  ;       | | ")
    print("                                             \-_   `;;._   ( `  /  /_       | | ")
    print("                                              `-.-.// ,'`-._\__/_,'         ; | ")
    print("                                                 \:: :     /     `     ,   /  | ")
    print("                                                  ||                ,'   /    | ")
    print("                                                  ||                ,'   /    | ")
    skip()
    empty(30)


    
    print("The hacker has likely already changed your password to something else,")
    print("so we have no choice but to return the favor...")
    print("")
    print("There are three ways to do this: BRUTE FORCE, MAN IN THE MIDDLE, and SQL INJECTION")
    print("")
    print("For reference, you were hacked with a simple phishing trick, but the hacker will")
    print("probably be smart enough to not enter his password *willingly*,")
    print("so we'll use something a little more advanced...")
    print("")
    skip()

#Brute force functions
def bruteforce_explain():

    print("")
    print("")
    print("")
    print("          ________                  ")
    print("      (( /========\                 ")
    print("      __/__________\____________n_  ")
    print("  (( /              \_____________] ")
    print("    /  =(*)=          \             ")
    print("    |_._._._._._._._._.|         !  ")
    print("(( / __________________ \       =o  ")
    print("  | OOOOOOOOOOOOOOOOOOO0 |   =      ")
    print("")
    print("")
    print(" The first method is commonly called a brute force attack,")
    print(" but you may know it as 'guessing...' ")
    print("")
    print("")
    print(" The idea is simple, there are 67 characters often used to create passwords.")
    print("")
    print(" Specifically, those characters are:")
    print("")
    print(" abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!$%_-") # I used an abbreviated version, full 94-char string: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`-=[]\;',./~!@#$%^&*()_+{}|":?><
    print("")
    print("")
    print("")
    skip()
def bruteforce_prompt():
    print(" ______________________________________________________________________________ ")
    print("|     Fortunately, we won't have to guess passwords ourselves.                 |")
    print("|     Rather, the computer will do it for us!                                  |")
    print("|     The program is in python, and looks something like this:                 |")
    print("|     --------------------------------------------------------------------     |")
    time.sleep(3)
    print("|                                                                              |")
    time.sleep(.1)
    print("| az = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!$%_-'   |")
    time.sleep(.1)
    print("|                                                                              |")
    time.sleep(.1)
    print("|  for i in range(len(az))                                                     |")
    time.sleep(.1)
    print("|    for j in range(len(az))                                                   |")
    time.sleep(.1)
    print("|      for k in range(len(az))                                                 |")
    time.sleep(.1)
    print("|        for l in range(len(az))                                               |")
    time.sleep(.1)
    print("|          for m in range(len(az))                                             |")
    time.sleep(.1)
    print("|            for n in range(len(az))                                           |")
    time.sleep(.1)
    print("|              for o in range(len(az))                                         |")
    time.sleep(.1)
    print("|                for p in range(len(az))                                       |")
    time.sleep(.1)
    print("|                  guess = az[i]+az[j]+az[k]+az[l]+az[m]+az[n]+az[o]+az[p]     |")
    time.sleep(.1)
    print("|                  try(guess)                                                  |")
    time.sleep(.1)
    print("|                                                                              |")
    time.sleep(.1)
    print("|     --------------------------------------------------------------------     |")
    time.sleep(.1)
    print("|     Run this command to get started:                                         |")
    time.sleep(.1)
    print("|                                                                              |")
    time.sleep(.1)
    print("|     sudo python3 /home/Users/downloads/bf_attack.py                          |")
    time.sleep(.1)
    print("|______________________________________________________________________________|")
    time.sleep(.1)

    while True:
        bfcommand = input("(base) User@Computer ~ % ")
        if bfcommand == ("sudo python3 /home/Users/downloads/bf_attack.py"):
            break
        else:
            print("zsh: command not found:" + bfcommand)
def bruteforce_simulate(): ### I originally had the script actually print out every combination, but the online interpreters couldn't handle it ;(
    wheel = 0
    progress = 0
    while True:
        if wheel == 0:
            spinner = "- "
        elif wheel == 1:
            spinner = "\ "
        elif wheel == 2:
            spinner = "| "
        elif wheel == 3:
            spinner = "/"
        elif wheel == 4:
            wheel = 0
            spinner = "- "

        print(" Running /home/Users/downloads/bf_attack.py   " + spinner)
        wheel += 1
        if progress == 0:
            print("--------------------------------------------------")
        if progress == 1:
            print("##------------------------------------------------")
        if progress == 2:
            print("####----------------------------------------------")
        if progress == 3:
            print("######--------------------------------------------")
        if progress == 4:
            print("########------------------------------------------")
        if progress == 5:
            print("##########----------------------------------------")
        if progress == 6:
            print("############--------------------------------------")
        if progress == 7:
            print("##############------------------------------------")
        if progress == 8:
            print("################----------------------------------")
        if progress == 9:
            print("##################--------------------------------")
        if progress == 10:
            print("####################------------------------------")
        if progress == 11:
            print("######################----------------------------")
        if progress == 12:
            print("########################--------------------------")
        if progress == 13:
            print("##########################------------------------")
        if progress == 14:
            print("############################----------------------")
        if progress == 15:
            print("##############################--------------------")
        if progress == 16:
            print("################################------------------")
        if progress == 17:
            print("##################################----------------")
        if progress == 18:
            print("####################################--------------")
        if progress == 19:
            print("######################################------------")
        if progress == 20:
            print("########################################----------")
        if progress == 21:
            print("##########################################--------")
        if progress == 22:
            print("############################################------")
        if progress == 23:
            print("##############################################----")
        if progress == 24:
            print("################################################--")
        if progress == 25:
            print("##################################################")

        elif progress > 25: # when done
            empty(30)
            break
        progress += 1
        empty(15)
        time.sleep(2)
        empty(15)




    
    print("That was just over 20 million guesses, and it took about a minute to complete.")
    time.sleep(.1)
    print("At 4 characters (20 million guesses) per 1 minute it would take:")
    time.sleep(.1)
    print("")
    time.sleep(5)
    print("67 minutes for 5 characters,")
    time.sleep(1)
    print("74.8 hours for 6 characters,")
    time.sleep(1)
    print("172,104 years for 10 characters,")
    time.sleep(1)
    print("and,")
    time.sleep(.5)
    print("232363266562 millennia for twenty characters.")
    print("")
    skip()
    empty(30 )
    
    print("So this could work if the hacker has a short password,")
    print("but this will take a lot of time. Time we simply don't have.")
    print("")
    print("We could also speed this up by trading in whatever lemon you're currently")
    print(" using right now for a NASA computer.")
    print("")
    print("Or by running the script in a more complex, but much faster, language like 'C'")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    skip()




# Man in the middle functions
def mitm_sim():
    empty(30)

    print("                 So, that didn't work, but I have another idea!")
    time.sleep(.1)
    print("")
    time.sleep(.1)
    print("                We could try a Man in the Middle (MitM) attack!")
    time.sleep(.1)
    slide(12)
    time.sleep(5)
    slide(30)
    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    print("                            _______                                             ")
    print("                           |.-----.|          In an MitM attack, we'll listen   ")
    print("                           ||     ||          to the conversation between the   ")
    print("                    YOU    ||_.-._||          hacker's computer and the wifi    ")
    print("                    ARE    `--)-(--`          router. Then we'll try to decrypt ")
    print("                    HERE  __[=== o]___        the messages and see if your      ")
    print("                         |:::::::::::|\       password is in there.             ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    print("")
    print(" enter 'y' to begin the attack...")
    print("")
    while True: # Continue?
        yn = input("Continue? (y/n):   ")
        if yn == "y":
            break
        elif yn == "n":
            print("Too bad, we're doing this thing anyways...")
            time.sleep(3)
            break
        else:
            print("ERROR: expected 'y' or 'n' but got " + yn + " instead")

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    print("                            _______                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    time.sleep(.2)
    #

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    print("                            _______                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    #
    
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                                                                                ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                                                                                ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                                                             |__|   ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                                                             |  |   ")
    print("   ')_____('                 || ||                                       |__|   ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                                                             |--|   ")
    print("   |'-----'|                 || ||                                       |  |   ")
    print("   ')_____('                 || ||                                       |__|   ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =========================================================  |=.|   ")
    print("   ||     ||                 || ||                                       |--|   ")
    print("   |'-----'|                 || ||                                       |  |   ")
    print("   ')_____('                 || ||                                       |__|   ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  ================   ======================================  |=.|   ")
    print("   ||     ||                \\   //                                      |--|   ")
    print("   |'-----'|                 || ||                                       |  |   ")
    print("   ')_____('                 || ||                                       |__|   ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                             || ||                                              ")
    print("                            _||_||_                                             ")
    print("                           |.-----.|                                            ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    
    #
    time.sleep(.2)

    print("________________________________________________________________________________")
    print("   HACKER'S                                                PUBLIC WIFI ROUTER   ")
    print("   COMPUTER                                                              .--.   ")
    print("   .-------.                    ENCYRPTED CONNECTION                     |__|   ")
    print("   |.-----.|  =============.  ] [  .==================================   |=.|   ")
    print("   ||     ||                \ | | /                                      |--|   ")
    print("   |'-----'|                 || ||                                       |  |   ")
    print("   ')_____('                 || ||                                       |__|   ")
    print("                             || ||                                              ")
    print("                             || ||            CONNECTION SUCCESS!               ")
    print("                             || ||            In just a second we should        ")
    print("                            _||_||_           start to see the intercepted      ")
    print("                           |.-----.|          data...                           ")
    print("                           ||     ||                                            ")
    print("                    YOU    ||_.-._||                                            ")
    print("                    ARE    `--)-(--`                                            ")
    print("                    HERE  __[=== o]___                                          ")
    print("                         |:::::::::::|\                                         ")
    print("                         `-=========-`()                                        ")
    print("--------------------------------------------------------------------------------")
    print("")
    print("")
    print("")
    time.sleep(5)
    print("1 Booting Sketch. ")
    time.sleep(.5)
    print("2 firmware v1.0 ")
    time.sleep(.5)
    print("3 ")
    time.sleep(.5)
    print("4 Update: v2. ino.bin ")
    time.sleep(.5)
    print("5 sleep disable ")
    time.sleep(1.2)
    print("6 Chunk 1 size: 2048 Hash: 22c47838cb13932a3ac369f14e3532cf6a99b399 ")
    time.sleep(.2)
    print("7 Chunk 2 size: 2048 Hash: ebzaacf95642ff895ded64ad4ca86ea6c3c7ec84 ")
    time.sleep(.2)
    print("8 Chunk 3 size: 2048 Hash: 0e682492ab3a819805c7a3043cd6caa441d69de3 ")
    time.sleep(.2)
    print("9 Chunk 4 size: 2048 Hash: 181652e107cdl62d3356cfdlce57b322alf5c14b ")
    time.sleep(.2)
    print("10 Chunk 5 size: 2048 Hash: fa50f70248c8512a7a2a323b89694ef52229712a ")
    time.sleep(.5)
    print("11 ...")
    time.sleep(.6)
    print("12 Chunk 145 size: 2048 Hash: 42734ab9b4cf8bf26a4ca06667e67d404bdb57f9 ")
    time.sleep(.4)
    print("13 Chunk 146 size: 148 Hash: 2ddf057494744c9cb5d647afc62424940bcad109 ")
    time.sleep(1.5)
    print("14 final hash is 6026c76c5ld4592124ded04292b0759le0165633 ")
    time.sleep(.5)
    print("15 Verifying with blockchain...")
    time.sleep(2.)
    print("16 Hyperledger Client Token: eyhbGciOiJIUzIlNiIsInR5cCI6Ik...PsCYTme ")
    time.sleep(.5)
    print("17 {'fon': 'verify' ")
    time.sleep(.3)
    print("18 'args': [ 'ESP00001', 6026c76c51d4592124ded04292b0759le0165633']} ")
    time.sleep(.2)
    print("19 Transaction ID: ")
    time.sleep(.5)
    print("20 969a9557dcb03e7e4d5c7076152567fac054c372981c99123585a26872612980 ")
    time.sleep(.5)
    print("21 'status' : 'unverified', 'failed attempts': 1} ")
    time.sleep(.5)
    print("22 Firmware hash does NOT match. Failed attempts made: 1")
    time.sleep(.5)
    print("23 Verification FAILED! OTA update aborted! Will REBOOT! ")
    time.sleep(2)
    print("24 ")
    time.sleep(.1)
    print("25 Booting Sketch... ")
    time.sleep(1.5)
    print("26 firmware v1.0 ")
    print("")
    skip()
    slide(30)
def mitm_analysis():
    
    print("                                                                /     |         ")
    print("                                                               /      |         ")
    print("                                                              /       |         ")
    print("                                                         ___,'        |         ")
    print("                                                       <  -'          :         ")
    print("                                                        `-.__..--'``-,_\_       ")
    print("                                                           |o/ ` o  )_`>        ")
    print("                                                           ;/ `     ||/)        ")
    print("                                                           (_.).__,-` |\        ")
    print("  ____________________________________                     /( `.``   `| :       ")
    print(" |                                    |                    \'`-.)  `  ; ;       ")
    print(" |  So that didn't quite go to plan,  |                    | `       /-<        ")
    print(" |  and I'll explain why.             |                    |     `  /   `.      ")
    print(" |____________________________________|    ,-_-..____     /|  `    :__..-'\     ")
    print("                                          /,'-.__\\  ``-./ :`      ;       \    ")
    print("                                          `\ `\  `\\  \ :  (   `  /  ,   `. \   ")
    print("                                            \` \   \\   |  | `   :  :     .\ \  ")
    print("                                             \ `\_  ))  :  ;     |  |      ): : ")
    print("                                            (`-.-'\ ||  |\ \   ` ;  ;       | | ")
    print("                                             \-_   `;;._   ( `  /  /_       | | ")
    print("                                              `-.-.// ,'`-._\__/_,'         ; | ")
    print("                                                 \:: :     /     `     ,   /  | ")
    print("                                                  ||                ,'   /    | ")
    print("                                                  ||                ,'   /    | ")
    skip()
    slide(30)

    print(" The MitM returns encrypted data encoded by a one-way hash algorithm.")
    print("")
    print("")
    time.sleep(.05)
    print(" Chunk 1 size: 2048 Hash: 22c47838cb13932a3ac369f14e3532cf6a99b399")
    time.sleep(.05)
    print(" Chunk 2 size: 2048 Hash: ebzaacf95642ff895ded64ad4ca86ea6c3c7ec84 ")
    time.sleep(.05)
    print(" Chunk 3 size: 2048 Hash: 0e682492ab3a819805c7a3043cd6caa441d69de3 ")
    time.sleep(.05)
    print(" Chunk 4 size: 2048 Hash: 181652e107cdl62d3356cfdlce57b322alf5c14b ")
    time.sleep(.05)
    print(" Chunk 5 size: 2048 Hash: fa50f70248c8512a7a2a323b89694ef52229712a ")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print(" ...")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print(" Chunk 145 size: 2048 Hash: 42734ab9b4cf8bf26a4ca06667e67d404bdb57f9 ")
    time.sleep(.05)
    print(" Chunk 146 size: 148 Hash: 2ddf057494744c9cb5d647afc62424940bcad109 ")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print("This data also seems to be salted, meaning it has random characters thrown in to")
    time.sleep(.05)
    print("throw off hackers like...")
    time.sleep(.05)
    print("...well...")
    time.sleep(.05)
    print("...like you, I suppose...")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    print("")
    time.sleep(.05)
    skip()

def sqli():

    print("                                                                                ")
    print("                                                                                ")
    print("     Ok, I hvave one more idea, but it's a little complicated and may require   ")
    print("     some critical thinking.                                                    ")
    print("                                                                                ")
    print("  _____  _____ _       _____ _   _    ___ _____ _____ _____ _____ _____ _   _ _ ")
    print(" /  ___||  _  | |     |_   _| \ | |  |_  |  ___/  __ \_   _|_   _|  _  | \ | | |")
    print(" \ `--. | | | | |       | | |  \| |    | | |__ | /  \/ | |   | | | | | |  \| | |")
    print("  `--. \| | | | |       | | | . ` |    | |  __|| |     | |   | | | | | | . ` | |")
    print(" /\__/ /\ \/' / |____  _| |_| |\  |/\__/ / |___| \__/\ | |  _| |_\ \_/ / |\  |_|")
    print(" \____/  \_/\_\_____/  \___/\_| \_/\____/\____/ \____/ \_/  \___/ \___/\_| \_(_)")
    print(" ------------------------------------------------------------------------------ ")
    print("  Ok so this will take some explaining...                                       ")
    print("                                                                                ")
    print("  Structured Query Language (SQL) is a special programming language used to     ")
    print("   write and read information to a database (a spreadsheet)                     ")
    print("                                                                                ") 
    print("  If a website has a login page in which blindly passes any text input into an  ")
    print("   SQL request, you can trick the database into telling you it's data.          ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    print("                                                                                ")
    skip()

    print("")
    print(" If you type some SQL code into the text box where you're supposed to search")
    print("  for a product, the database will blindly execute our injection (virus).")
    print("")
    print(" Normally, the user will type in a query into the search box, their input")
    print("  is then added to the end of a SQL query which returns a list of products")
    print("  matching the search query. Stay with me here...")
    print("")
    print(" In other words, anything we type in will be added to the command below, then")
    print("   sent to the database to be executed (* means all):")
    print("")
    print(" SELECT * FROM collectables WHERE name = {our input inserted here}")
    print("")
    print(" We can't control the entire command, just the bit in {brackets}. But we can ")
    print("  still take advantage of that! I know... resist the boredom, you can do it!!!")
    print("")
    print(" Now, if we enter some SQL code in the username box instead of an actual search")
    print("  the database will, for example, spit out its contents. STAY WITH ME!")
    print("")
    print(" First, try entering a single quote where the website asks for a username.")
    print(" This will create an unclosed quote inside the aforementioned SQL command and")
    print(" break the SQL command. I'll pull up the website now so you can try it.")
    print("")
    skip()

    print(" _____________________________________________________________________________ ")
    print("|                                                                             |")
    print("|                                                                             |")
    print("|                                                                             |")
    print("|     Welcome to NFTrader: The 143rd most popular NFT trading website!        |")
    print("|                                                                             |")
    print("|     Search for an NFT to continue: [_____]                                  |")
    print("|                                                                             |")
    print("|_____________________________________________________________________________|")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("    Ok, try entering a lone quote (') to test the system")
    print("")
    print("    If the website throws an error, then there is no protection against these")
    print("     kinds of special requests. REMEMBER THE STAKES HERE! RESIST THE BOREDOM!!!")
    print("")
    print("")
    print("")
    print("")
    print("")
    nft_search = ("")
    while True:
        nft_search = input("Search for an NFT to continue: ")

        if nft_search == ("'"):
            break # if ' is enter, loop will break and script will move on. Other wise, script will request input again.
        else:
            print("Remember, only enter a single quote (') to test the system!")
    
    empty(30)
    print("|------------------------------------------------------------------------------|")
    print("|                Whoops! Something went wrong with our servers                |")
    print("|            We apologize for the inconvenience. Please try again!             |")
    print("|______________________________________________________________________________|")
    empty(8)
    print("  Perfect! This means the website is vulnerable and we can begin our attack...  ")
    print("")
    skip()
    empty(30)

    print(" Try this:")
    print(" Type anything, followed by a single quote ('), then add a semicolon.")
    print(" This will create a valid request, which is then invalidated by the single quote")
    print("")
    print(" The semicolon will tell the script to treat whatever comes next as a new command")
    print("")
    print(" So after the semicolon, we can add whatever SQL command we want, and")
    print("   the databse will recognize it as a new command! Hopefully you're starting to")
    print("   see just how dangerous this you were a malicious hacker! Stay with me on this.")
    print("")
    print(" Fortunately, most websites have protection against these kinds of attacks, but")
    print("   fortunately for your account, this website doesn't have any countermeasures.")
    print("")
    print(" Just as a reminder, this is what the command being fed to the database looks")
    print("   like, we can't control the parts in (parenthesis), the part in {brackets}")
    print("   is where the command we enter in the username box will be inserted, and")
    print("   the part in [square brackets] is where our secret command will be run:")
    print("")
    print(" (SELECT * FROM collectables WHERE name = ){John'; [secret command] }")
    skip()

    print("")
    print("To recap, use this injection to get into the database:")
    print("")
    print(" ';UPDATE users SET password = 'password' WHERE name = 'your username' ")
    print("")
    print(" Ok, now put it all together, remember, the single quote breaks and cancels out")
    print("   the 'real' code programmed by the site's creator. The semicolon tells")
    print("   the code to treat whatever comes next as a new command. And the code after")
    print("   the semicolon is the virus injection which the databse will execute")
    print("")
    print(" When you enter the command yourself, replace 'password' with a placeholder")
    print("   hashed password the hacker won't have access to, use:")
    print("   'fa50f70248c8512a7a2a' as a placeholder, you can change this later.")
    print("   Use the username you used when you created your account a few minutes ago.")
    print(" _____________________________________________________________________________ ")
    print("|                                                                             |")
    print("|                                                                             |")
    print("|                                                                             |")
    print("|     Welcome to NFTrader: The 143rd most popular NFT trading website!        |")
    print("|                                                                             |")
    print("|     Search for an NFT to continue: [_____]                                  |")
    print("|                                                                             |")
    print("|_____________________________________________________________________________|")

    while True:
        sqli_command = input("Search for an NFT to continue: ")
        if sqli_command == "';UPDATE users SET password = fa50f70248c8512a7a2a WHERE name = " + username:
            break
        else:
            print("Hey user, this doesn't seem right, double check your command and try again.")
            print("If you forget what you're doing, you can always scroll up a bit.")
            print("")

def conclusion():
    empty(30)
    time.sleep(3)
    print(".")
    time.sleep(.25)
    empty(30)
    print("..")
    time.sleep(.25)
    empty(30)
    print("...")
    time.sleep(.25)
    empty(30)
    print("...I")
    time.sleep(.1)
    empty(30)
    print("...I ")
    time.sleep(.1)
    empty(30)
    print("...I t")
    time.sleep(.1)
    empty(30)
    print("...I th")
    time.sleep(.1)
    empty(30)
    print("...I thi")
    time.sleep(.1)
    empty(30)
    print("...I thin")
    time.sleep(.1)
    empty(30)
    print("...I think")
    time.sleep(.1)
    empty(30)
    print("...I think ")
    time.sleep(.1)
    empty(30)
    print("...I think i")
    time.sleep(.1)
    empty(30)
    print("...I think it")
    time.sleep(.1)
    empty(30)
    print("...I think it ")
    time.sleep(.1)
    empty(30)
    print("...I think it w")
    time.sleep(.1)
    empty(30)
    print("...I think it wo")
    time.sleep(.1)
    empty(30)
    print("...I think it wor")
    time.sleep(.1)
    empty(30)
    print("...I think it work")
    time.sleep(.1)
    empty(30)
    print("...I think it worke")
    time.sleep(.1)
    empty(30)
    print("...I think it worked")
    time.sleep(.1)
    time.sleep(.25)
    empty(30)
    print("...I think it worked.")
    time.sleep(.25)
    empty(30)
    print("...I think it worked..")
    time.sleep(.25)
    empty(30)
    print("...I think it worked...")
    time.sleep(2)
    slide(30)

    print("  Try logging in again with the unhashed version of the password you injected.")
    print("                      into the database just a second ago:")
    print("")
    print("                            ThEUlt1mat3P455W0Rd!?!?")
    print("")
    print("")
    print(" _____________________________________________________________________________ ")
    print("|                             NFTrader Login Page                             |")
    print("|                                                                             |")
    print("|          USERNAME: " + username) #Since the length of the username changes, I can't have a set '|' on the right side of this line...
    print("|                                                                             |")
    print("|          PASSWORD: __________                                               |")
    print("|                                                                             |")
    print("|                                                                             |")
    print("|_____________________________________________________________________________|")

    while True:
        login_check = input("Enter your password: ")


        if login_check == password:
            break
        else:
            print("Invalid password: '" + login_check + "'")
            print("")
            print("Remember user, your temporary password is: ThEUlt1mat3P455W0Rd!?!?")
            print("")
    
    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                               LOGIN SUCCESSFUL!                               |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)
    
    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                               LOGIN SUCCESSFUL                               |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)
    
    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                               LOGIN SUCCESSFUL!                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)
    
    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                               LOGIN SUCCESSFUL!                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")

    time.sleep(.5)

    print(" ______________________________________________________________________________ ")
    print("|                                                                              |")
    print("|                              ---YOUR WALLET---                               |")
    print("|                                                                              |")
    print("|   Current NFTs Owned:  1                                                     |")
    print("|                                                                              |")
    print("|   Total account value: 3 ether (8,174.46 USD)                                |")
    print("|                                                                              |")
    print("|           ACCOUNT RESTORED!!! GAME WON!!! THANK YOU FOR PLAYING!!!           |")
    print("|                                                                              |")
    print("|                                 __,_,                                        |")
    print("|                                [_|_/                                         |")
    print("|                                 //                                           |")
    print("|                               _//    __                                      |")
    print("|                              (_|)   |@@|                                     |")
    print("|                               \ \__ \--/ __                                  |")
    print("|                                \o__|----|  |   __                            |")
    print("|                                    \ }{ /\ )_ / _\                           |")
    print("|                                    /\__/\ \__O (__                           |")
    print("|                                   (--/\--)    \__/                           |")
    print("|                                   _)(  )(_                                   |")
    print("|                                  `---''---`                                  |")
    print("--------------------------------------------------------------------------------")
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)
    print("")
    time.sleep(.3)

    

    








################################################## STORYLINE ##################################################


splashscreen()

# Enter a password
password = enter_password()
username = enter_username()

# Where am I?
empty(30)
thankyou() # STATUS QUO
time.sleep(.5)

# PWNED
phishing() # CALL TO ACTION

while True: # Enter password to verify identity / PWNED!!!
    pw_check = input("Enter your password: ")


    if pw_check == password:

        # "verifing" the password (not actually verifying, ofc)

        empty(30)
        print("VERIFING PASSWORD: --------------------------------------------------")
        empty(20)
        time.sleep(.5)
        print("VERIFING PASSWORD: #-------------------------------------------------")
        empty(20)

        time.sleep(.5)
        print("VERIFING PASSWORD: ##------------------------------------------------")
        empty(20)

        time.sleep(.5)
        print("VERIFING PASSWORD: ###-----------------------------------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: ####----------------------------------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: ###########---------------------------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: ###########---------------------------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: ############################----------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: #############################---------------------")
        empty(20)
        
        time.sleep(.5)
        print("VERIFING PASSWORD: ##########################################--------")
        empty(20)

        time.sleep(.5)
        print("VERIFING PASSWORD: #################################################-")
        empty(20)

        time.sleep(1)
        print("VERIFING PASSWORD: ##################################################")
        empty(30)
        time.sleep(1)

        print("")
        time.sleep(.5)
        print("PASSWORD SUCCESSFULLY VERIFIED")



        time.sleep(2)

        print("                           ____,                ")
        print("                          /.---|                ")
        print("                          `    |     ___        ")
        print("                              (=\.  /-. \       ")
        print("                               |\/\_|''| |      ")
        print("                               |_\ |;- / ;      ")
        print("                               | / \| |_/ \     ")
        print("                               | )/\/      \    ")
        print("                               | ( '|  \   |    ")
        print("                               |    \_ /   \    ")
        print("                               |    /  \_.--\   ")
        print("                               \    |    (|\`   ")
        print("                                |   |     \     ")
        print("                                |   |      '.   ")
        print("                                |  /         \  ")
        print("                                \  \.__.__.-._) ")
        print("")
        print("                     TERRIBLE SORRY, BUT YOU'VE  BEEN")
        print("              _______          ___   _ ______ _____  _ _ _  ")
        print("             |  __ \ \        / | \ | |  ____|  __ \| | | | ")
        print("             | |__) \ \  /\  / /|  \| | |__  | |  | | | | | ")
        print("             |  ___/ \ \/  \/ / | . ` |  __| | |  | | | | | ")
        print("             | |      \  /\  /  | |\  | |____| |__| |_|_|_| ")
        print("             |_|       \/  \/   |_| \_|______|_____/(_(_(_) ")
        time.sleep(5)

        break # Break the loop so my computer won't catch on fire.

# WAIT
meetmentor() # (MEETING THE MENTOR)
time.sleep(.5)
empty(30)

### BRUTE FORCE ATTACK (CROSSING THE THRESHOLD / TRIALS)
bruteforce_explain() # Explains how brute force works
bruteforce_prompt() # Fake script execution
bruteforce_simulate() # Real script execution

### MAN IN THE MIDDLE ATTACK (TRIALS)
mitm_sim()
mitm_analysis()

### SQLI ATTACK (ORDEAL / REBIRTH) (Death and rebirth is boredom.)
sqli()

### FIN ###
conclusion() # (ROAD BACK / STATUS QUO)

time.sleep(10)

# There's almost as many LINES in this file as there are WORDS in my final reflection...

##################################################   Clu: [chuckles] End of line, man.   ##################################################